# See https://help.github.com/articles/configuring-jekyll/
name: Cargo Media
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
paginate: 6
paginate_path: "/blog/page:num"
gems:
 - jekyll-coffeescript
 - jekyll-paginate
exclude: ['/tmp', '/node_modules', '/vendor']
